# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: text_classifier.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15text_classifier.proto\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"T\n\x16\x43lassificationResponse\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x14\n\x0chandler_time\x18\x03 \x01(\x02\x32I\n\x0eTextClassifier\x12\x37\n\x0c\x43lassifyText\x12\x0c.TextRequest\x1a\x17.ClassificationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text_classifier_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTREQUEST']._serialized_start=25
  _globals['_TEXTREQUEST']._serialized_end=52
  _globals['_CLASSIFICATIONRESPONSE']._serialized_start=54
  _globals['_CLASSIFICATIONRESPONSE']._serialized_end=138
  _globals['_TEXTCLASSIFIER']._serialized_start=140
  _globals['_TEXTCLASSIFIER']._serialized_end=213
# @@protoc_insertion_point(module_scope)
